



















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `CCBlogDbContext`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=(LocalDB)\v11.0;AttachDbFilename=C:\GitHubSrc\CCBlog\CCBlog.Web\App_Data\CCBlog.mdf;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=30`
//     Schema:                 ``
//     Include Views:          `False`



using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;

namespace CCBlog.Model.Poco
{

	public partial class CCBlogDbContext : Database
	{
		public CCBlogDbContext() 
			: base("CCBlogDbContext")
		{
			CommonConstruct();
		}

		public CCBlogDbContext(string connectionStringName) 
			: base(connectionStringName)
		{
			CommonConstruct();
		}
		
		partial void CommonConstruct();
		
		public interface IFactory
		{
			CCBlogDbContext GetInstance();
		}
		
		public static IFactory Factory { get; set; }
        public static CCBlogDbContext GetInstance()
        {
			if (_instance!=null)
				return _instance;
				
			if (Factory!=null)
				return Factory.GetInstance();
			else
				return new CCBlogDbContext();
        }

		[ThreadStatic] static CCBlogDbContext _instance;
		
		public override void OnBeginTransaction()
		{
			if (_instance==null)
				_instance=this;
		}
		
		public override void OnEndTransaction()
		{
			if (_instance==this)
				_instance=null;
		}
        

	}
	




	[TableName("[dbo].[sysdiagrams]")]



	[PrimaryKey("diagram_id")]



	[ExplicitColumns]
    public partial class sysdiagram  
    {



		[Column] public string name { get; set; }





		[Column] public int principal_id { get; set; }





		[Column] public int diagram_id { get; set; }





		[Column] public int? version { get; set; }





		[Column] public byte[] definition { get; set; }



	}


	[TableName("[CCBlog].[Role]")]



	[PrimaryKey("RoleId")]



	[ExplicitColumns]
    public partial class Role  
    {



		[Column] public int RoleId { get; set; }





		[Column] public string Name { get; set; }



	}


	[TableName("[CCBlog].[Tag]")]



	[PrimaryKey("TagId")]



	[ExplicitColumns]
    public partial class Tag  
    {



		[Column] public int TagId { get; set; }





		[Column] public string Name { get; set; }





		[Column] public string Title { get; set; }





		[Column] public string HelpText { get; set; }





		[Column] public bool IsVisible { get; set; }





		[Column] public bool IsNavigation { get; set; }





		[Column] public int? DisplayOrder { get; set; }



	}


	[TableName("[CCBlog].[PostTag]")]



	[PrimaryKey("PostId", autoIncrement=false)]

	[ExplicitColumns]
    public partial class PostTag  
    {



		[Column] public int PostId { get; set; }





		[Column] public int TagId { get; set; }



	}


	[TableName("[CCBlog].[Series]")]



	[PrimaryKey("SeriesId")]



	[ExplicitColumns]
    public partial class Series  
    {



		[Column] public int SeriesId { get; set; }





		[Column] public string Name { get; set; }





		[Column] public string Title { get; set; }





		[Column] public string Abstract { get; set; }





		[Column("StatusId")] public CCBlog.Model.Contracts.EntityStatus Status { get; set; }



	}


	[TableName("[CCBlog].[Post]")]



	[PrimaryKey("PostId")]



	[ExplicitColumns]
    public partial class Post  
    {



		[Column] public int PostId { get; set; }





		[Column] public string UrlFriendlyName { get; set; }





		[Column] public string Title { get; set; }





		[Column] public string Abstract { get; set; }





		[Column] public string Body { get; set; }





		[Column] public DateTimeOffset CreateDate { get; set; }





		[Column] public DateTimeOffset ModifyDate { get; set; }





		[Column] public DateTimeOffset AuthorCreateDate { get; set; }





		[Column] public DateTimeOffset AuthorModifyDate { get; set; }





		[Column] public int CreatedByUserId { get; set; }





		[Column] public int ModifiedByUserId { get; set; }





		[Column] public int RevisionCount { get; set; }





		[Column] public string TagIdCsv { get; set; }





		[Column] public int? SeriesId { get; set; }





		[Column] public int? SeriesPart { get; set; }





		[Column] public int? DisplayOrder { get; set; }





		[Column] public string PageLayoutName { get; set; }





		[Column("StatusId")] public CCBlog.Model.Contracts.EntityStatus Status { get; set; }



	}


	[TableName("[CCBlog].[User]")]



	[PrimaryKey("UserId")]



	[ExplicitColumns]
    public partial class User  
    {



		[Column] public int UserId { get; set; }





		[Column] public string ClaimedIdentifier { get; set; }





		[Column] public string FullName { get; set; }





		[Column] public string Email { get; set; }





		[Column] public string Nickname { get; set; }





		[Column] public bool IsAuthor { get; set; }





		[Column] public int? RoleId { get; set; }



	}


}



